 export const DataMovies=
 [
  {id:"1", name: "Nemo", description:"Released on May 30, 2003, Finding Nemo won the Academy Award for Best Animated Feature, the first Pixar film to do so. It was also nominated in three more categories, including Best Original Screenplay. Additionally, it became the highest-grossing animated film at the time of its release, and was the second-highest-grossing film of 2003, earning a total of $871 million worldwide by the end of its initial theatrical run.", image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3Za-zIALUUm5BJQGk68dSIIaL2Smt5A1Atw&usqp=CAU", rating:"9"},
  {id:"2", name: "Industructibles 2", description:"Incredibles 2 is a 2018 American computer-animated superhero film produced by Pixar Animation Studios and released by Walt Disney Pictures. Written and directed by Brad Bird, it is the sequel to The Incredibles (2004) and the second full-length installment of the franchise.", image:"https://cdn.shopify.com/s/files/1/1416/8662/products/incredibles_2_2018_french_grande_a_original_film_art_1200x.jpg?v=1588448598", rating:"8"},
  {id:"3", name: "FROZEN 2", description:"Frozen II is a 2019 American computer-animated musical fantasy film produced by Walt Disney Animation Studios and distributed by Walt Disney Studios Motion Pictures.", image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRymPFXWIwNdX_IcAGSkurXvVnjSmdFtNUrOg&usqp=CAU", rating:"8"},
  {id:"4", name: "Hotel Transylvania", description:"Hotel Transylvania is a media franchise created by comedy writer Todd Durham. It consists of three theatrical films (along with an upcoming film), three graphic novels and two short films produced by Sony Pictures Animation, as well as a traditionally-animated TV series broadcast on Disney Channel and several video games.", image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtjPjT6h-jXU2jeqhumQB7Vs227344CEIfNo2Kic6cu6C6maDd", rating:"8"},
  {id:"5", name: "UP", description:"Up is a 2009 American computer-animated comedy-drama adventure film produced by Pixar Animation Studios and released by Walt Disney Pictures.", image:"https://i.pinimg.com/originals/85/45/03/854503affab6d3e789cca6c7d393b5b1.jpg", rating:"8"},
  {id:"1", name: "The Godfather", description:"The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.", image:"https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UY1200_CR107,0,630,1200_AL_.jpg", rating:"9"},
  {id:"2", name: "The Godfather: Part II", description:"The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.", image:"https://m.media-amazon.com/images/M/MV5BMWMwMGQzZTItY2JlNC00OWZiLWIyMDctNDk2ZDQ2YjRjMWQ0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg", rating:"9"},
  {id:"3", name: "The Godfather: Part III", description:"In the midst of trying to legitimize his business dealings in New York City and Italy in 1979, aging Mafia Don Michael Corleone seeks to avow for his sins, while taking his nephew Vincent Mancini under his wing.", image:"https://m.media-amazon.com/images/M/MV5BNTc1YjhiNzktMjEyNS00YmNhLWExYjItZDhkNWJjZjYxOWZiXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UY1200_CR85,0,630,1200_AL_.jpg", rating:"7"},
  {id:"4", name: "Scarface", description:"In 1980 Miami, a determined Cuban immigrant takes over a drug cartel and succumbs to greed.", image:"https://i.pinimg.com/736x/9e/35/14/9e35144ffc01d001cbed59029728115f.jpg", rating:"8"},
  {id:"5", name: "Goodfellas", description:"The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito in the Italian-American crime syndicate.", image:"https://m.media-amazon.com/images/M/MV5BY2NkZjEzMDgtN2RjYy00YzM1LWI4ZmQtMjIwYjFjNmI3ZGEwXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg", rating:"8"},
  {id:"6", name: "A Bronx Tale", description:"A father becomes worried when a local gangster befriends his son in the Bronx in the 1960s.", image:"https://m.media-amazon.com/images/M/MV5BOGU5MmQzMzYtZjQ4MS00YmU1LWEzYmYtMzdlNjI4OWE4M2YwXkEyXkFqcGdeQXVyNDY2MTk1ODk@._V1_.jpg", rating:"8"},
  {id:"7", name: "Heat", description:"A group of professional bank robbers start to feel the heat from police when they unknowingly leave a clue at their latest heist.", image:"https://m.media-amazon.com/images/M/MV5BNGMwNzUwNjYtZWM5NS00YzMyLWI4NjAtNjM0ZDBiMzE1YWExXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_.jpg", rating:"8"},
  {id:"8", name: "Carlito's Way", description:"A Puerto Rican former convict, just released from prison, pledges to stay away from drugs and violence despite the pressure around him and lead on to a better life outside of N.Y.C.", image:"https://m.media-amazon.com/images/M/MV5BN2I2N2Q1YmMtMzZkMC00Y2JjLWJmOWUtNjc2OTM2ZTk1MjUyXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg", rating:"8"},
]
